#!/usr/bin/env bash

# Fast compile check using Rider's bundled MSBuild (no Unity Editor required).
# Note: This does NOT regenerate the .sln/.csproj files. If you added/removed .cs/asmdefs,
# run rebuildSolutionFromUnityItself.sh instead.

set -euo pipefail

PROJECT_PATH="$(pwd)" 

# Replace "LightECS.sln" with your <Unity_Project.sln> that is generated by Unity Editor.
SOLUTION_UNIX="$PROJECT_PATH/LightECS.sln"
SOLUTION="$(cygpath -w "$SOLUTION_UNIX")"

RiderLOG_FILE="$PROJECT_PATH/CI/RiderMsBuild.log"
UnityCOMPILEError_FILE="$PROJECT_PATH/CI/CompileErrorsAfterUnityRun.log"
# .log are ignore by .gitignore, so that git process will not interfere with writing into it (required, otherwise it will lock the file).
UnityCOMPILEErrorFinal="$PROJECT_PATH/CI/CompileErrorsAfterUnityRun.txt"

MSBUILD_DEFAULT="/c/Program Files/JetBrains/JetBrains Rider 2025.1.4/tools/MSBuild/Current/Bin/amd64/MSBuild.exe"
MSBUILD="${RIDER_MSBUILD:-$MSBUILD_DEFAULT}"

echo
echo "MSBuild path:"
echo "$MSBUILD"
echo

echo "Project path:"
echo "$PROJECT_PATH"
echo

echo "Solution path:"
echo "$SOLUTION_UNIX"
echo

echo "Rider build log path:"
echo "$RiderLOG_FILE"
echo

echo "Compile errors path:"
echo "$UnityCOMPILEError_FILE"
echo

: > "$UnityCOMPILEErrorFinal"
: > "$RiderLOG_FILE"
: > "$UnityCOMPILEError_FILE"

if [[ ! -f "$SOLUTION_UNIX" ]]; then
  echo "Solution not found: $SOLUTION_UNIX"
  exit 1
fi

if [[ ! -x "$MSBUILD" ]]; then
  echo "MSBuild not found or not executable: $MSBUILD"
  echo "Set RIDER_MSBUILD to your MSBuild.exe path if different."
  exit 1
fi

# Prevent Git Bash path conversion on MSBuild switches like /t:/m:/p: and /nologo.
set +e
MSYS2_ARG_CONV_EXCL="*" "$MSBUILD" \
  "$SOLUTION" \
  /t:Rebuild \
  /m \
  /v:m \
  /nologo \
  /p:Configuration=Debug \
  /p:Platform="Any CPU" \
  2>&1 | tee "$RiderLOG_FILE"

echo "Finished with wiring log"
echo "Make sure call echo twice"

if [[ ! -f "$RiderLOG_FILE" ]]; then
  echo "RiderLOG_FILE file not found: $RiderLOG_FILE"
  exit 1
fi

if [[ ! -s "$RiderLOG_FILE" ]]; then
  echo "RiderLOG_FILE file is empty: $RiderLOG_FILE"
fi

if [[ ! -f "$UnityCOMPILEError_FILE" ]]; then
  echo "Compile error file not found: $UnityCOMPILEError_FILE"
  exit 1
fi

echo "Compile error file can be found at path: $UnityCOMPILEError_FILE"

# Extract C# compile errors (CRLF-safe).
awk '
  { sub(/\r$/, "", $0) }
  tolower($0) ~ /error cs/ { print }
' "$RiderLOG_FILE" > "$UnityCOMPILEError_FILE"

echo "Waiting log..."
echo "Waiting log..."

cat "$UnityCOMPILEError_FILE" > "$UnityCOMPILEErrorFinal"
echo "Waiting copy..."
echo "Waiting copy..."


if [[ -s "$UnityCOMPILEError_FILE" ]]; then
  echo "Compile errors found; dumped to $UnityCOMPILEErrorFinal"
  exit 1
else
  echo "Compile succeeded: no compile time errors."
fi
